//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaleManager.locale.zh_CN {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocaleManager.locale.zh_CN.Forms", typeof(Forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑器.
        /// </summary>
        internal static string CellEditor {
            get {
                return ResourceManager.GetString("CellEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改变语言.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建新的地区支持.
        /// </summary>
        internal static string CreateNewLocale {
            get {
                return ResourceManager.GetString("CreateNewLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已有地区支持：.
        /// </summary>
        internal static string ExistingLocales {
            get {
                return ResourceManager.GetString("ExistingLocales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提取.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale Manager -  支持 RESX 和 PROPERTIES 文件.
        /// </summary>
        internal static string MainFormCaption {
            get {
                return ResourceManager.GetString("MainFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择基本地区文件夹.
        /// </summary>
        internal static string SelectBase {
            get {
                return ResourceManager.GetString("SelectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择的地区支持：.
        /// </summary>
        internal static string SelectedLocales {
            get {
                return ResourceManager.GetString("SelectedLocales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作表格.
        /// </summary>
        internal static string WorkSheetForm {
            get {
                return ResourceManager.GetString("WorkSheetForm", resourceCulture);
            }
        }
    }
}
